#include <cmath>
#include <iomanip>
#include <iostream>

#include "polyfit/polyfit.hpp"

namespace {

// Series fallback avoids the cancellation in sin(t) - t and cos(t) - 1 near u = 0.
long double sin_tail_u_series(long double u) {
    const long double c8 = -1.0L / 51090942171709440000.0L;
    const long double c7 = 1.0L / 355687428096000.0L;
    const long double c6 = -1.0L / 1307674368000.0L;
    const long double c5 = 1.0L / 6227020800.0L;
    const long double c4 = -1.0L / 39916800.0L;
    const long double c3 = 1.0L / 362880.0L;
    const long double c2 = -1.0L / 5040.0L;
    const long double c1 = 1.0L / 120.0L;
    const long double c0 = -1.0L / 6.0L;
    return ((((((((c8 * u + c7) * u + c6) * u + c5) * u + c4) * u + c3) * u + c2) * u + c1) * u + c0);
}

long double cos_tail_u_series(long double u) {
    const long double c8 = -1.0L / 6402373705728000.0L;
    const long double c7 = 1.0L / 87178291200.0L;
    const long double c6 = -1.0L / 2092278988800.0L;
    const long double c5 = 1.0L / 479001600.0L;
    const long double c4 = -1.0L / 3628800.0L;
    const long double c3 = 1.0L / 40320.0L;
    const long double c2 = -1.0L / 720.0L;
    const long double c1 = 1.0L / 24.0L;
    const long double c0 = -1.0L / 2.0L;
    return ((((((((c8 * u + c7) * u + c6) * u + c5) * u + c4) * u + c3) * u + c2) * u + c1) * u + c0);
}

template<class Eval>
void print_coeff_array(const char *name, const Eval &eval) {
    std::cout << "inline constexpr std::array<double, " << eval.nCoeffs() << "> " << name << " = {\n";
    std::cout << std::hexfloat;
    for (std::size_t i = 0; i < eval.nCoeffs(); ++i) {
        std::cout << "    " << eval.coeffs()[i];
        if (i + 1 != eval.nCoeffs()) std::cout << ',';
        std::cout << '\n';
    }
    std::cout << "};\n\n" << std::defaultfloat;
}

} // namespace

int main() {
    const double pi = poly_eval::detail::constants::pi;
    const double pio4 = pi / 4.0;
    const double uhi = pio4 * pio4;

    const auto sin_tail = poly_eval::fit<6>(
        [](double u) {
            const long double ul = static_cast<long double>(u);
            if (std::fabs(ul) < 1.0e-8L) return static_cast<double>(sin_tail_u_series(ul));
            const long double t = std::sqrt(ul);
            return static_cast<double>((std::sin(t) - t) / (t * t * t));
        },
        0.0, uhi, poly_eval::FuseAlways{});
    const auto cos_tail = poly_eval::fit<6>(
        [](double u) {
            const long double ul = static_cast<long double>(u);
            if (std::fabs(ul) < 1.0e-8L) return static_cast<double>(cos_tail_u_series(ul));
            const long double t = std::sqrt(ul);
            return static_cast<double>((std::cos(t) - 1.0L) / (t * t));
        },
        0.0, uhi, poly_eval::FuseAlways{});

    std::cout << "// Regenerated by portable_trig_generate.cpp\n";
    std::cout << "// See portable_trig_generate.cpp for the exact stable u-domain fit kernels.\n\n";
    print_coeff_array("sin_coeffs", sin_tail);
    print_coeff_array("cos_coeffs", cos_tail);
    return 0;
}
