#!/usr/bin/env python3
"""Amalgamate polyfit into a single header.

Usage:
  python3 scripts/amalgamate.py [--root ROOT] [--input INPUT] [--output OUTPUT]

Defaults:
  --root    .                                  (repo root)
  --input   include/polyfit/fast_eval.hpp      (public umbrella header)
  --output  include/polyfit/polyfit.hpp        (generated single header)

Only headers resolved within ROOT/include/polyfit are inlined.
System headers (<...>) and external project headers (xsimd, poet, mdspan)
are preserved as #include directives.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Patterns
# ---------------------------------------------------------------------------
_RE_PRAGMA_ONCE = re.compile(r"^\s*#\s*pragma\s+once\s*$", re.MULTILINE)
_RE_INCLUDE_GUARD_IFNDEF = re.compile(r"^\s*#\s*ifndef\s+\w+\s*$", re.MULTILINE)
_RE_INCLUDE_GUARD_DEFINE = re.compile(r"^\s*#\s*define\s+\w+\s*$", re.MULTILINE)
# Match local includes: #include "..." or #include "path/to/..."
_RE_LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s+"([^"]+)"', re.MULTILINE)

_BANNER = """\
// =============================================================================
// polyfit — single-header amalgamation
// Generated by scripts/amalgamate.py — do not edit manually.
//
// Dependencies (must be on your include path):
//   * xsimd        https://github.com/xtensor-stack/xsimd
//   * poet         https://github.com/DiamonDinoia/poet
//   * kokkos/mdspan (C++17) or std::mdspan (C++23+)
// =============================================================================
"""


def strip_guards(text: str) -> str:
    """Remove #pragma once and a single outermost #ifndef / #define guard pair."""
    # Strip pragma once
    text = _RE_PRAGMA_ONCE.sub("", text)

    # Strip a leading include-guard ifndef + define (first occurrence pair only)
    lines = text.splitlines(keepends=True)
    out: list[str] = []
    guard_ifndef_removed = False
    guard_define_removed = False
    for i, line in enumerate(lines):
        if not guard_ifndef_removed and _RE_INCLUDE_GUARD_IFNDEF.match(line):
            guard_ifndef_removed = True
            continue
        if guard_ifndef_removed and not guard_define_removed and _RE_INCLUDE_GUARD_DEFINE.match(line):
            guard_define_removed = True
            continue
        out.append(line)

    # If we removed the opening guard, remove the matching trailing #endif
    if guard_ifndef_removed:
        # Walk backwards and remove the last #endif
        for i in range(len(out) - 1, -1, -1):
            if re.match(r"^\s*#\s*endif\b", out[i]):
                out.pop(i)
                break

    return "".join(out)


def inline_file(
    path: Path,
    root: Path,
    processed: set[Path],
    depth: int = 0,
) -> str:
    """Recursively inline a header file, replacing local includes with content."""
    path = path.resolve()
    if path in processed:
        return f"// (already inlined: {path.relative_to(root)})\n"
    processed.add(path)

    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return f"// WARNING: could not open {path}\n"

    # Strip header guards from files being inlined (not the top-level entry)
    if depth > 0:
        text = strip_guards(text)

    result_parts: list[str] = []

    if depth > 0:
        rel = path.relative_to(root)
        result_parts.append(f"\n// BEGIN_FILE: {rel}\n")

    pos = 0
    for m in _RE_LOCAL_INCLUDE.finditer(text):
        # Emit text before this include
        result_parts.append(text[pos : m.start()])
        pos = m.end()

        include_name = m.group(1)
        # Resolve relative to the directory of the current file
        candidate = (path.parent / include_name).resolve()

        # Only inline if the file lives inside root/include/polyfit
        polyfit_include = (root / "include" / "polyfit").resolve()
        if candidate.exists() and str(candidate).startswith(str(polyfit_include)):
            inlined = inline_file(candidate, root, processed, depth + 1)
            result_parts.append(inlined)
        else:
            # Not a polyfit-internal header — keep as-is (treated as external)
            result_parts.append(m.group(0) + "\n")

    # Emit remaining text after last include
    result_parts.append(text[pos:])

    if depth > 0:
        rel = path.relative_to(root)
        result_parts.append(f"\n// END_FILE: {rel}\n")

    return "".join(result_parts)


def build_single_header(root: Path, input_path: Path, output_path: Path) -> None:
    processed: set[Path] = set()
    content = inline_file(input_path, root, processed, depth=0)

    # Ensure the output starts with #pragma once
    if not _RE_PRAGMA_ONCE.search(content):
        content = "#pragma once\n\n" + content

    output = _BANNER + "\n" + content

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8")
    n_inlined = len(processed)
    print(f"Amalgamated {n_inlined} file(s) -> {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=".", help="Repository root directory")
    parser.add_argument("--input", default="include/polyfit/fast_eval.hpp", help="Entry-point header")
    parser.add_argument("--output", default="include/polyfit/polyfit.hpp", help="Output single-header path")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    input_path = (root / args.input).resolve()
    output_path = (root / args.output).resolve()

    if not input_path.exists():
        print(f"Error: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    build_single_header(root, input_path, output_path)


if __name__ == "__main__":
    main()
